### ISSUE TITLE
[C++ API] undefined reference to CNTK::Function::LoadModel

### ISSUE THREAD

**Issue by Netzeband** [Microsoft/CNTK#1774]
Hi

I'm working on Ubuntu and use the precompiled CNTK library V2.0rc1.

The following file does not compile on my system, due to missing references:
```cpp
#include <iostream>
#include <CNTKLibrary.h>

int main()
{
  auto Function = CNTK::Function::LoadModel(L"Model.dnn");
  return 0;
}
```
Compile-Output:
```
/usr/bin/c++    -I/home/robot/cntk/Include  -O3 -DNDEBUG   -std=c++11 -o CMakeFiles/eval.dir/main.cpp.o -c /Projects/SAM/CNTKEvaluation/AlexNetInCPP/main.cpp
[100%] Linking CXX executable eval
/usr/bin/cmake -E cmake_link_script CMakeFiles/eval.dir/link.txt --verbose=1
/usr/bin/c++   -O3 -DNDEBUG   CMakeFiles/eval.dir/main.cpp.o  -o eval  -L/home/robot/cntk/cntk/lib -lCntk.Core-2.0rc1 -lCntk.Deserializers.Binary-2.0rc1 -lCntk.Math-2.0rc1 -lCntk.PerformanceProfiler-2.0rc1 -lCntk.Reader.SparsePC-2.0rc1 -lCntk.Reader.HTKMLF-2.0rc1 -lCntk.Deserializers.HTK-2.0rc1 -lCntk.Eval-2.0rc1 -lCntk.Reader.LMSequence-2.0rc1 -lCntk.Reader.LUSequence-2.0rc1 -lCntk.Reader.SVMBinary-2.0rc1 /home/robot/cntk/cntk/lib/libmultiverso.so -lCntk.Composite-2.0rc1 -lCntk.Reader.Kaldi2-2.0rc1 -lCntk.Reader.UCIFast-2.0rc1 -lCntk.Deserializers.TextFormat-2.0rc1 -lCntk.Deserializers.Image-2.0rc1 -Wl,-rpath,/home/robot/cntk/cntk/lib: 
CMakeFiles/eval.dir/main.cpp.o: In function `main':
main.cpp:(.text.startup+0x9f): undefined reference to `CNTK::Function::LoadModel(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, CNTK::DeviceDescriptor const&)'
collect2: error: ld returned 1 exit status
```

As you can see, every available library file from directory cntk/lib is linked to my project. I really have no idea where this reference is contained.
Does it probably not work with the shared lib?

**Comment by zhouwangzw** [comment]
Which GCC version are you using? The pre-compiled library is using GCC 4.8, as described here: https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Linux.

**Comment by Netzeband** [comment]
I'm using Gcc 5.4.0. Do you think this happens due to an incompability of the compilers?

**Comment by OleStauning** [comment]
Your code compiles fine on my computer with gcc version 4.8.4, using:

g++ -std=c++11  main.cpp -I /cntk/Source/CNTKv2LibraryDll/API/ -I /cntk/Source/ComputationNetworkLib/ -I /cntk/Source/Common/Include/ -I /cntk/Source/Math/ /cntk/build/cpu/release/lib/libcntklibrary-2.0.so

I can recommend using the docker-files to "downgrade" the compiler. I never got the CNTK code to compile under gcc version 6.2.0, which is the normal compiler on my Kubuntu version.

**Comment by Netzeband** [comment]
Hi Ole

I do not have this library file on my precompiled CNTK setup. It is not contained in the lib directory. Maybe it is missing in the Installation package?

**Comment by OleStauning** [comment]
Hi,

I can see the library names have [changed](https://github.com/Microsoft/CNTK/wiki/CNTK-Shared-Libraries-Naming-Format). So the new name of the library should be "libCntk.Core-2.0rc2d.so". I have not tested the pre-compiled library myself. Once I got the docker image working the configure-script worked and I compiled the libraries myself.

**Comment by Netzeband** [comment]
Yes this is the library I used. Thanks for clarification. So either using the docker image or compile the lib on my system is the next step. 

I will close the issue now.

Thanks for all your input about that issue.
