### ISSUE TITLE
Undefined reference error while building CNTK 2.4

### ISSUE THREAD

**Issue by psn9** [Microsoft/CNTK#2976]
Hi,

I am facing the following error while build CNTK 2.4 at commit 11425634b5a224bec7960d7db5b2d0e1495c2b64 .

```
build/release/lib/libCntk.Math-2.4.so: undefined reference to `Microsoft::MSR::CNTK::File::PutMarker(Microsoft::MSR::CNTK::FileMarker, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)'

build/release/lib/libCntk.Math-2.4.so: undefined reference to `Microsoft::MSR::CNTK::DebugUtil::GetCallStack(unsigned long, bool)'

build/release/lib/libCntk.Math-2.4.so: undefined reference to `Microsoft::MSR::CNTK::File::GetMarker(Microsoft::MSR::CNTK::FileMarker, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)'
```

What am I missing ?

**Comment by psn9** [comment]
Got it resolved after updating gcc to 5.4.0.

`mpic++ -v` was pointing to gcc 5.4.0 , but the default `gcc -v` was pointing to 4.8.x.

Made default gcc point to 5.4.0 and the issue resolved.
