### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by rakesh-sbm** [Microsoft/CNTK#862]
i followed every step as described, and then running into this build error. Any help ?

[build.txt](https://github.com/Microsoft/CNTK/files/486610/build.txt)

**Comment by n17s** [comment]
What's the output of g++ --version on your system?

**Comment by rakesh-sbm** [comment]
g++ (Ubuntu 4.9.3-13ubuntu2) 4.9.3

**Comment by junjieqian** [comment]
The recommended g++ is 4.8.4, as in [link](https://github.com/Microsoft/CNTK/wiki/Test-Configurations). The explanation why this error happens is [here](http://stackoverflow.com/questions/26947704/implicit-conversion-failure-from-initializer-list).

**Comment by rakesh-sbm** [comment]
Thanks.. I changed the g++ to 4.8, and now I get this error:

Source/Math/CPUSparseMatrix.cpp:350:13: error: ‘::isnan’ has not been declared

the header included in CPUSparseMatrix.cpp is <math.h> instead of <cmath>

full build log attached:
[debug_log.txt](https://github.com/Microsoft/CNTK/files/488057/debug_log.txt)

**Comment by junjieqian** [comment]
This can be solved by changing to "std::isnan", as one closed [pull](https://github.com/Microsoft/CNTK/pull/778/files).

**Comment by n17s** [comment]
Why did you close this Junjie? std::isnan works on 4.8.5. is it not supported on 4.8.4? Or is it a problem with visual studio? All these can be fixed with the appropriate #ifdef

**Comment by junjieqian** [comment]
I will submit the changes later. It has to be std::isnan in later gcc versions (5.1.3 in my case). And, I agree with you that the appropriate #ifdef can avoid such problems (different usages in windows and linux).

**Comment by budiryan** [comment]
Is it possible to manually make changes to the source code without breaking the framework? 

I am trying to build CNTK into a cluster. Unfortunately, I do not have any admin privilege and could not update the gcc version of the cluster

**Comment by junjieqian** [comment]
@budiryan can you describe the need with more details? In general, you can always clone the source tree and build CNTK with the way you want.
