### ISSUE TITLE
Running python on self built binaries locally

### ISSUE THREAD

**Issue by championoaks** [Microsoft/CNTK#2245]
After lot of struggle I got python 3.5 +Anaconda running but, learnt that fastRCNN only works with 3.4 and python script wasn't using my binaries. Then I switched over to using 3.4 by uninstalling everything but it never worked.

C:\Windows\system32>activate cntk-py34
(cntk-py34) F:\users\localuser\cntk-2.X\CNTK\Tutorials\NumpyInterop>python FeedForwardNet.py
Traceback (most recent call last):
  File "FeedForwardNet.py", line 8, in <module>
    from cntk.device import cpu, try_set_default_device
  File "F:\users\localuser\cntk-2.X\CNTK\bindings\python\cntk\__init__.py", line 10, in <module>
    from . import cntk_py
ImportError: cannot import name 'cntk_py'

==================
In Visual studio "Python Bindings" project is also failing to compile
>  FileNotFoundError: [Errno 2] No such file or directory: 'F:\\users\\localuser\\cntk-2.X\\CNTK\\x64\\Release_CpuOnly\\Cntk.Deserializers.Binary-2.1.dll'
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets(41,5): error MSB3073: The command ".\vsbuild.bat "F:\users\localuser\cntk-2.X\CNTK\x64\Release_CpuOnly\" "false" "false" "2.1" "C:\local\swigwin-3.0.10" "" "" "C:\Anaconda3\envs\cntk-py34" "" """ **exited with code 1.**
========== Build: 0 succeeded, 1 failed, 13 up-to-date, 0 skipped ==========

These are the two env variables
 CNTK_PY34_PATH C:\Anaconda3\envs\cntk-py34
PYTHONPATH F:\users\localuser\cntk-2.X\CNTK\bindings\python

**Comment by tangyuq** [comment]
Your SWIG project seems not built correctly. How did you build CNTK? 

If you just want to use CNTK without changing the source code, an easier step is to :
activate cntk-py34
pip install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.1-cp34-cp34m-win_amd64.whl

Then you should have the cntk-py34 environment with CNTK installed.

**Comment by n17s** [comment]
You have to figure out the reason  why Cntk.Deserializers.Binary-2.1.dll was not built. Maybe you are missing a dependency, or you did not build all dependencies before compiling the python bindings.

**Comment by Meai1** [comment]
I also have this problem, I'm not a python expert. I have no clue how to solve this. As you can see, I already imported the PYTHONPATH correctly. What else could be wrong? I built from source release.

> pc@linux-94q0:/home/pc/cntk/CNTK/Examples/LanguageUnderstanding/ATIS/Python> export PYTHONPATH=/home/pc/cntk/CNTK/bindings/python
> pc@linux-94q0:~/cntk/CNTK/Examples/LanguageUnderstanding/ATIS/Python> python ./LanguageUnderstanding.py 
> Traceback (most recent call last):
>   File "./LanguageUnderstanding.py", line 11, in <module>
>     import cntk
>   File "/home/pc/cntk/CNTK/bindings/python/cntk/__init__.py", line 10, in <module>
>     from . import cntk_py
> ImportError: cannot import name cntk_py
>
