### ISSUE TITLE
cntk>=2.4 don't compiles with gcc-4.9: codecvt error

### ISSUE THREAD

**Issue by MalKeshar** [Microsoft/CNTK#3138]
cntk: 2.5.1
gcc: 4.9.4

Step to reproduce:

```
../sources/configure --with-buildtype=release --asgd=yes --with-openblas=/jet --with-libzip=/jet --with-boost=/jet --with-protobuf=/jet --with-opencv=/jet --mpi=yes --with-mpi=/jet && make all
```

Errors:

```
...
creating /jet/tmp/build/.build/Source/CNTK/BrainScript/BrainScriptEvaluator.o for Linux with build type release
...
In file included from Source/SGDLib/DataReaderHelpers.h:9:0,
                 from Source/SGDLib/SimpleOutputWriter.h:10,
                 from Source/EvalDll/CNTKEval.cpp:18:
Source/ComputationNetworkLib/SpecialPurposeNodes.h:21:19: fatal error: codecvt: No such file or directory
...
```

gcc-4.9 don't have directory codecvt, it for gcc>=5.

``` 
$ find gcc-cxx-4.9.4/ -name codecvt
$ find gcc-cxx-[56]* -name codecvt
gcc-cxx-5.4.0/include/c++/codecvt
gcc-cxx-6.3.0/include/c++/codecvt
```

Ok. As I see in ./Source/Readers/LUSequenceReader/Exports.cpp it should be optional
 
```
void EnableUTF8Support() 
{
    // TODO: codecvt should be supported in the latest gcc,
    // remove the #ifdef when we move to 5.3.
#ifdef _MSC_VER
    locale::global(locale(locale::empty(), new codecvt_utf8<wchar_t>));
#else
```

Let's patch problem place

```
$ git diff 
diff --git a/Source/ComputationNetworkLib/SpecialPurposeNodes.h b/Source/ComputationNetworkLib/SpecialPurposeNodes.h
index 9411d29..c0ee1ab 100755
--- a/Source/ComputationNetworkLib/SpecialPurposeNodes.h
+++ b/Source/ComputationNetworkLib/SpecialPurposeNodes.h
@@ -18,7 +18,9 @@
 #include <list>
 #include <memory>
 #include <locale>
+#ifdef _MSC_VER
 #include <codecvt>
+#endif
 
 namespace Microsoft { namespace MSR { namespace CNTK {
 ```

Let's try again. No success

 ```
In file included from Source/SGDLib/DataReaderHelpers.h:9:0,
                 from Source/SGDLib/SimpleEvaluator.h:16,
                 from Source/ActionsLib/EvalActions.cpp:18:
Source/ComputationNetworkLib/SpecialPurposeNodes.h: In member function 'void Microsoft::MSR::CNTK::LatticeSequenceWithSoftmaxNode<ElemType>::LoadConfigsFromFile()':
Source/ComputationNetworkLib/SpecialPurposeNodes.h:881:9: error: 'wstring_convert' is not a member of 'std'
         std::wstring_convert<std::codecvt_utf8<wchar_t>, wchar_t> converter;
         ^
Source/ComputationNetworkLib/SpecialPurposeNodes.h:881:30: error: 'codecvt_utf8' is not a member of 'std'
         std::wstring_convert<std::codecvt_utf8<wchar_t>, wchar_t> converter;
                              ^
Source/ComputationNetworkLib/SpecialPurposeNodes.h:881:48: error: expected primary-expression before 'wchar_t'
         std::wstring_convert<std::codecvt_utf8<wchar_t>, wchar_t> converter;
                                                ^
Source/ComputationNetworkLib/SpecialPurposeNodes.h:882:44: error: 'converter' was not declared in this scope
         std::string latticeConfigPathStr = converter.to_bytes(m_latticeConfigPath);
 ```

**Comment by thiagocrepaldi** [comment]
Hi MalKeshar, your guess is right ! Officially, CNTK 2.4+ must be compiled using GCC 5.3, which is the default on Ubuntu 16.04. However, you are welcome to send us a PR with required changes to support older GCCs too :)

**Comment by MalKeshar** [comment]
Thank you for information. I suggest,  theese ifdefs are wrong then. 
And it would be nice to have proper information about system requirements, or any kind updates in release notes. I don't find any.

**Comment by thiagocrepaldi** [comment]
https://docs.microsoft.com/en-us/cognitive-toolkit/setup-cntk-on-linux#c-compiler instructs users to execute "dpkg --list | grep compiler" and compare the output to "g++-5 5.4.0-6ubuntu1~16.04.5 amd64 GNU C++ compiler" to check compiler.
